[package]
name = "snake"
version = "0.1.0"
edition = "2021"
author = ["raahimfareed <raahim1965@hotmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.3.18"
piston_window = "0.74.0"